services:
  bedrock:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bedrock-dev
    ports:
      - "8888:8888"
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
    networks:
      - bedrock
    depends_on:
      - mongodb_container
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mongodb://mongodb_container:27017/bedrock
    restart: unless-stopped

  mongodb_container:
    image: mongo:7
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bedrock
    restart: unless-stopped

networks:
  bedrock:
    driver: bridge

volumes:
  mongodb_data:
