name: CD Pipeline

on:
  workflow_run: 
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:

    - name: Create Network
      run: |
        sudo docker network create bedrock || true


    - name: Delete all running containers and images
      run: |
        sudo docker ps -q | xargs -r sudo docker rm -f
        sudo docker images -q | xargs -r sudo docker rmi -f

    - name: Pull Docker image
      run: |
        sudo docker pull creepereye12/bedrock:latest 
        sudo docker pull creepereye12/nginx:latest

    

    - name: Run Docker Container
      run: |
        sudo docker run --name bedrock -d -p 8888:8888 creepereye12/bedrock:latest
        sudo docker run --name nginx -d -p 80:80 -p 443:443 creepereye12/nginx:latest

    - name: Delete Docker image
      run: |
        sudo docker rmi creepereye12/bedrock:latest || true
        sudo docker rmi creepereye12/nginx:latest || true
      
      
