name: CD Pipeline

on:
  workflow_run: 
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:

    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


    - name: Ensure Docker Network Exists
      run: |
        sudo docker network inspect bedrock >/dev/null 2>&1 || docker network create bedrock

    - name: Stop and Remove All Containers
      run: |
        sudo docker ps -q | xargs -r docker stop || true
        sudo docker ps -aq | xargs -r docker rm -f || true

    - name: Remove All Docker Images
      run: |
        sudo docker images -q | xargs -r docker rmi -f || true

    - name: Pull Latest Docker Images
      run: |
        sudo docker pull creepereye12/bedrock:latest
        sudo docker pull creepereye12/nginx:latest

    - name: Run Docker Containers
      run: |
        sudo docker run -d \
        --name bedrock \
        --network bedrock \
        -p 8888:8888 \
        creepereye12/bedrock:latest

        sudo docker run --name nginx --network bedrock -d -p 80:80 -p 443:443 creepereye12/nginx:latest



    - name: Optionally Delete Pulled Images
      run: |
        sudo docker rmi creepereye12/bedrock:latest || true
        sudo docker rmi creepereye12/nginx:latest || true