name: CD Pipeline

on:
  workflow_run: 
  workflows: ["CI Pipeline"]
  types:
    - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull creepereye12/bedrock:latest
    - name: Delete Old docker container
      run: sudo docker rm -f bedrock || true
    - name: Run Docker Container
      run: sudo docker run --name bedrock -d -p 8888:8888 creepereye12/bedrock:latest
    - name: Delete Docker image
      run: sudo docker rmi creepereye12/bedrock:latest || true
      
      
