name: CD Pipeline

on:
  workflow_run: 
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:

    - name: Ensure Docker Network Exists
      run: |
        docker network inspect bedrock >/dev/null 2>&1 || docker network create bedrock

    - name: Stop and Remove All Containers
      run: |
        docker ps -q | xargs -r docker stop || true
        docker ps -aq | xargs -r docker rm -f || true

    - name: Remove All Docker Images
      run: |
        docker images -q | xargs -r docker rmi -f || true

    - name: Pull Latest Docker Images
      run: |
        docker pull creepereye12/bedrock:latest
        docker pull creepereye12/nginx:latest

    - name: Run Docker Containers
      run: |
        docker run --name bedrock --network bedrock -d -p 8888:8888 creepereye12/bedrock:latest
        docker run --name nginx --network bedrock -d -p 80:80 -p 443:443 creepereye12/nginx:latest


    - name: Optionally Delete Pulled Images
      run: |
        docker rmi creepereye12/bedrock:latest || true
        docker rmi creepereye12/nginx:latest || true